import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import CaratLink from "../components/CaratLink";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yelink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/meng.png" />
      </Head>

      <Header />
      <main>
        <div className="mt-3 flex flex-col items-center px-4 text-center">
          <h1 className="text-3xl font-['Patrick Hand'] mb-1">Say The Name!</h1>
          <p className="text-[14px] font-['Rancho']">
            Hi! My name is Yelly. Full time Developer, Part time Carats <br />
            Wonwoo & DK. Hope you like my recommendation!
          </p>
        </div>
        <CaratLink />
      </main>
      <Footer carat={true} />
    </>
  );
};

export default Home;
