import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Greetings from "../components/Greetings";
import SocialLink from "../components/SocialLink";
import Footer from "../components/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Yelink</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        <Greetings />
        <SocialLink />
      </main>
      <Footer />
    </>
  );
};

export default Home;
